### ISSUE TITLE
Roadmap 1.0.0

### ISSUE THREAD

**Issue by iduuck** [fintory/flow-cov#12]
To just define a transparent roadmap, I would like to use this issue and just keep in up and running. Should be used as a living document.

**Upcoming:**
- [x] Bare construction – Ship the first v0.1.0
- [x] Write tests – Tests that don't fail and implement "OK"-ish coverage
- [x] Text Reporter – Just report a table in the console
- [x] JSON Reporter – e.g. exporting JSON as a file
- [x] `flow` options – let the user specify flow options that are straight passed (#13)
- [ ] Add option to disable failing when `flow status` fails
- [ ] Strict mode – Don't care about the `@flow` annotation (#14)
- [ ] HTML Reporter – e.g. for using artifacts in CircleCI

**Dismissed:**
- [ ] ~LCOV Reporter – e.g. for Codecov, Coveralls, ...~

**Comment by V1shvesh** [comment]
Hey @iDuuck ,
Let me know if I can do something to help

**Comment by iduuck** [comment]
@V1shvesh Feel free to pick one of the tasks and open a PR. I will review and merge if it's fine.
